// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: backend/v1/types.proto

package backendv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VerificationKind is the stage of a verification flow a step represents
// (domain.VerificationKind).
type VerificationKind int32

const (
	VerificationKind_VERIFICATION_KIND_UNSPECIFIED VerificationKind = 0
	VerificationKind_VERIFICATION_KIND_REQUESTED   VerificationKind = 1
	VerificationKind_VERIFICATION_KIND_SAS         VerificationKind = 2
	VerificationKind_VERIFICATION_KIND_DONE        VerificationKind = 3
	VerificationKind_VERIFICATION_KIND_CANCELED    VerificationKind = 4
	VerificationKind_VERIFICATION_KIND_RESTORED    VerificationKind = 5
)

// Enum value maps for VerificationKind.
var (
	VerificationKind_name = map[int32]string{
		0: "VERIFICATION_KIND_UNSPECIFIED",
		1: "VERIFICATION_KIND_REQUESTED",
		2: "VERIFICATION_KIND_SAS",
		3: "VERIFICATION_KIND_DONE",
		4: "VERIFICATION_KIND_CANCELED",
		5: "VERIFICATION_KIND_RESTORED",
	}
	VerificationKind_value = map[string]int32{
		"VERIFICATION_KIND_UNSPECIFIED": 0,
		"VERIFICATION_KIND_REQUESTED":   1,
		"VERIFICATION_KIND_SAS":         2,
		"VERIFICATION_KIND_DONE":        3,
		"VERIFICATION_KIND_CANCELED":    4,
		"VERIFICATION_KIND_RESTORED":    5,
	}
)

func (x VerificationKind) Enum() *VerificationKind {
	p := new(VerificationKind)
	*p = x
	return p
}

func (x VerificationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_v1_types_proto_enumTypes[0].Descriptor()
}

func (VerificationKind) Type() protoreflect.EnumType {
	return &file_backend_v1_types_proto_enumTypes[0]
}

func (x VerificationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationKind.Descriptor instead.
func (VerificationKind) EnumDescriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{0}
}

// Level is the bar a message clears to earn something (notify.Level).
type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	Level_LEVEL_NONE        Level = 1
	Level_LEVEL_MENTION     Level = 2
	Level_LEVEL_DM          Level = 3
	Level_LEVEL_ALL         Level = 4
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_NONE",
		2: "LEVEL_MENTION",
		3: "LEVEL_DM",
		4: "LEVEL_ALL",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_NONE":        1,
		"LEVEL_MENTION":     2,
		"LEVEL_DM":          3,
		"LEVEL_ALL":         4,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_v1_types_proto_enumTypes[1].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_backend_v1_types_proto_enumTypes[1]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{1}
}

// Room is a Matrix room we are in or have been invited to (domain.Room).
type Room struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDirect bool                   `protobuf:"varint,3,opt,name=is_direct,json=isDirect,proto3" json:"is_direct,omitempty"`
	Members  []string               `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	// Membership is "" for joined (domain.MembershipJoin, the zero value) or "invite".
	Membership string `protobuf:"bytes,5,opt,name=membership,proto3" json:"membership,omitempty"`
	InvitedBy  string `protobuf:"bytes,6,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	// Replacement is the room this one was upgraded into (m.room.tombstone's
	// replacement_room), empty for a room that has never been upgraded.
	Replacement string `protobuf:"bytes,7,opt,name=replacement,proto3" json:"replacement,omitempty"`
	// Topic is m.room.topic — the room's one-line description, and on a bridged room the
	// group description carried across by the bridge.
	Topic string `protobuf:"bytes,8,opt,name=topic,proto3" json:"topic,omitempty"`
	// Archived is the network's own archive holding the room (Telegram's Archived
	// folder, WhatsApp's archived chats); kith's archive tag follows it where configured.
	Archived bool `protobuf:"varint,9,opt,name=archived,proto3" json:"archived,omitempty"`
	// Forum marks a forum's own room (Telegram's General topic); the forum is a space
	// of its topics' rooms.
	Forum         bool `protobuf:"varint,10,opt,name=forum,proto3" json:"forum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_backend_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetIsDirect() bool {
	if x != nil {
		return x.IsDirect
	}
	return false
}

func (x *Room) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Room) GetMembership() string {
	if x != nil {
		return x.Membership
	}
	return ""
}

func (x *Room) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *Room) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

func (x *Room) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Room) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Room) GetForum() bool {
	if x != nil {
		return x.Forum
	}
	return false
}

// Mention is one @-mention within a message (domain.Mention).
type Mention struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of user_id and room_id is set.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RoomId string `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// The person's name in the room now, as the cache knows it (domain.Mention.Known).
	Known         string `protobuf:"bytes,4,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mention) Reset() {
	*x = Mention{}
	mi := &file_backend_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mention) ProtoMessage() {}

func (x *Mention) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mention.ProtoReflect.Descriptor instead.
func (*Mention) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Mention) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Mention) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mention) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Mention) GetKnown() string {
	if x != nil {
		return x.Known
	}
	return ""
}

// Media is a message attachment's display metadata (domain.Media).
type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "image" | "video" | "audio" | "file"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mime          string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Width         int64                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`   // pixels, 0 if unknown
	Height        int64                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"` // pixels, 0 if unknown
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`     // bytes, 0 if unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_backend_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Media) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Media) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Media) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Media) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Revision is one version of a message (domain.Revision).
type Revision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event that carried this wording.
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=at,proto3" json:"at,omitempty"`
	Format        *Formatted             `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"` // unset when the version is plain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_backend_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Revision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Revision) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Revision) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Revision) GetFormat() *Formatted {
	if x != nil {
		return x.Format
	}
	return nil
}

// Activity is what the other people in a room are doing right now (domain.Activity).
type Activity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Typing        []string               `protobuf:"bytes,2,rep,name=typing,proto3" json:"typing,omitempty"` // everyone typing right now, us excluded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_backend_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *Activity) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Activity) GetTyping() []string {
	if x != nil {
		return x.Typing
	}
	return nil
}

// Message is a single timeline message event (domain.Message).
type Message struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId     string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sender     string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderName string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Body       string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Redacted   bool                   `protobuf:"varint,7,opt,name=redacted,proto3" json:"redacted,omitempty"`
	Edited     bool                   `protobuf:"varint,8,opt,name=edited,proto3" json:"edited,omitempty"`
	ReplyTo    string                 `protobuf:"bytes,9,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Mentioned  bool                   `protobuf:"varint,10,opt,name=mentioned,proto3" json:"mentioned,omitempty"`
	Media      *Media                 `protobuf:"bytes,11,opt,name=media,proto3" json:"media,omitempty"` // unset when the message carries no attachment
	Mentions   []*Mention             `protobuf:"bytes,12,rep,name=mentions,proto3" json:"mentions,omitempty"`
	// An m.emote — what /me sends.
	Emote bool `protobuf:"varint,14,opt,name=emote,proto3" json:"emote,omitempty"`
	// The thread this message belongs to, empty when it is in the main timeline.
	ThreadRoot string `protobuf:"bytes,13,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	// Who removed the message, what they said about it, and when.
	RedactedBy       string `protobuf:"bytes,16,opt,name=redacted_by,json=redactedBy,proto3" json:"redacted_by,omitempty"`
	RedactedReason   string `protobuf:"bytes,17,opt,name=redacted_reason,json=redactedReason,proto3" json:"redacted_reason,omitempty"`
	RedactedAtUnixMs int64  `protobuf:"varint,18,opt,name=redacted_at_unix_ms,json=redactedAtUnixMs,proto3" json:"redacted_at_unix_ms,omitempty"`
	// When the edit now supplying body was sent, 0 when unedited or unknown: edits
	// arrive in any order, and only a newer one may replace it.
	EditedAtUnixMs int64 `protobuf:"varint,19,opt,name=edited_at_unix_ms,json=editedAtUnixMs,proto3" json:"edited_at_unix_ms,omitempty"`
	// The edit event now supplying body, empty when unedited: two edits sent in the same
	// millisecond are told apart by it, as the cache tells them apart.
	RevisionId string `protobuf:"bytes,20,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	// Sent because the edit this message showed was deleted: what it shows now, which
	// replaces the body and edit whatever their times (domain.Message.Reverted).
	Reverted bool `protobuf:"varint,21,opt,name=reverted,proto3" json:"reverted,omitempty"`
	// The formatting drawn over body, unset when the message is plain.
	Format *Formatted `protobuf:"bytes,22,opt,name=format,proto3" json:"format,omitempty"`
	// Placeholder marks a bridge's stand-in for a message it could not read yet, which
	// it replaces by an edit (domain.Message.Placeholder).
	Placeholder bool  `protobuf:"varint,23,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Poll        *Poll `protobuf:"bytes,24,opt,name=poll,proto3" json:"poll,omitempty"` // unset when the message asks no poll
	// Orders messages sharing a time, the larger the later; 0 for none
	// (domain.Message.Seq).
	Seq           int64 `protobuf:"varint,25,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_backend_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetRedacted() bool {
	if x != nil {
		return x.Redacted
	}
	return false
}

func (x *Message) GetEdited() bool {
	if x != nil {
		return x.Edited
	}
	return false
}

func (x *Message) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *Message) GetMentioned() bool {
	if x != nil {
		return x.Mentioned
	}
	return false
}

func (x *Message) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Message) GetMentions() []*Mention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *Message) GetEmote() bool {
	if x != nil {
		return x.Emote
	}
	return false
}

func (x *Message) GetThreadRoot() string {
	if x != nil {
		return x.ThreadRoot
	}
	return ""
}

func (x *Message) GetRedactedBy() string {
	if x != nil {
		return x.RedactedBy
	}
	return ""
}

func (x *Message) GetRedactedReason() string {
	if x != nil {
		return x.RedactedReason
	}
	return ""
}

func (x *Message) GetRedactedAtUnixMs() int64 {
	if x != nil {
		return x.RedactedAtUnixMs
	}
	return 0
}

func (x *Message) GetEditedAtUnixMs() int64 {
	if x != nil {
		return x.EditedAtUnixMs
	}
	return 0
}

func (x *Message) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *Message) GetReverted() bool {
	if x != nil {
		return x.Reverted
	}
	return false
}

func (x *Message) GetFormat() *Formatted {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *Message) GetPlaceholder() bool {
	if x != nil {
		return x.Placeholder
	}
	return false
}

func (x *Message) GetPoll() *Poll {
	if x != nil {
		return x.Poll
	}
	return nil
}

func (x *Message) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// Poll is a question a message asks (domain.Poll).
type Poll struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Options  []*PollOption          `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Multiple bool                   `protobuf:"varint,4,opt,name=multiple,proto3" json:"multiple,omitempty"`
	Closed   bool                   `protobuf:"varint,5,opt,name=closed,proto3" json:"closed,omitempty"`
	Quiz     bool                   `protobuf:"varint,6,opt,name=quiz,proto3" json:"quiz,omitempty"`
	Voters   int64                  `protobuf:"varint,7,opt,name=voters,proto3" json:"voters,omitempty"`
	// Each voter's answers, where the network tells votes one by one.
	Ballots       []*Ballot `protobuf:"bytes,8,rep,name=ballots,proto3" json:"ballots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_backend_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *Poll) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Poll) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Poll) GetOptions() []*PollOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Poll) GetMultiple() bool {
	if x != nil {
		return x.Multiple
	}
	return false
}

func (x *Poll) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *Poll) GetQuiz() bool {
	if x != nil {
		return x.Quiz
	}
	return false
}

func (x *Poll) GetVoters() int64 {
	if x != nil {
		return x.Voters
	}
	return 0
}

func (x *Poll) GetBallots() []*Ballot {
	if x != nil {
		return x.Ballots
	}
	return nil
}

// Ballot is one voter's answers in a poll.
type Ballot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voter         string                 `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ballot) Reset() {
	*x = Ballot{}
	mi := &file_backend_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ballot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ballot) ProtoMessage() {}

func (x *Ballot) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ballot.ProtoReflect.Descriptor instead.
func (*Ballot) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *Ballot) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *Ballot) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// PollOption is one answer of a poll.
type PollOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Votes         int64                  `protobuf:"varint,3,opt,name=votes,proto3" json:"votes,omitempty"`
	Mine          bool                   `protobuf:"varint,4,opt,name=mine,proto3" json:"mine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOption) Reset() {
	*x = PollOption{}
	mi := &file_backend_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOption) ProtoMessage() {}

func (x *PollOption) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOption.ProtoReflect.Descriptor instead.
func (*PollOption) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *PollOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PollOption) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PollOption) GetVotes() int64 {
	if x != nil {
		return x.Votes
	}
	return 0
}

func (x *PollOption) GetMine() bool {
	if x != nil {
		return x.Mine
	}
	return false
}

// Formatted is formatting as it draws (richtext.Formatted): the text, and the
// emphasized runs of it. Every network's own markup is converted in the daemon.
type Formatted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Spans         []*Span                `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Formatted) Reset() {
	*x = Formatted{}
	mi := &file_backend_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Formatted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formatted) ProtoMessage() {}

func (x *Formatted) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formatted.ProtoReflect.Descriptor instead.
func (*Formatted) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *Formatted) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Formatted) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

// Span is one emphasized run of Formatted.text, in UTF-8 byte offsets (richtext.Span).
type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Bold          bool                   `protobuf:"varint,3,opt,name=bold,proto3" json:"bold,omitempty"`
	Italic        bool                   `protobuf:"varint,4,opt,name=italic,proto3" json:"italic,omitempty"`
	Code          bool                   `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Strike        bool                   `protobuf:"varint,6,opt,name=strike,proto3" json:"strike,omitempty"`
	Underline     bool                   `protobuf:"varint,7,opt,name=underline,proto3" json:"underline,omitempty"`
	Link          bool                   `protobuf:"varint,8,opt,name=link,proto3" json:"link,omitempty"`
	Quote         bool                   `protobuf:"varint,9,opt,name=quote,proto3" json:"quote,omitempty"`
	Heading       bool                   `protobuf:"varint,10,opt,name=heading,proto3" json:"heading,omitempty"`
	Spoiler       bool                   `protobuf:"varint,11,opt,name=spoiler,proto3" json:"spoiler,omitempty"`
	Reason        string                 `protobuf:"bytes,12,opt,name=reason,proto3" json:"reason,omitempty"` // a spoiler's label
	Href          string                 `protobuf:"bytes,13,opt,name=href,proto3" json:"href,omitempty"`     // a link's target
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_backend_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *Span) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Span) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Span) GetBold() bool {
	if x != nil {
		return x.Bold
	}
	return false
}

func (x *Span) GetItalic() bool {
	if x != nil {
		return x.Italic
	}
	return false
}

func (x *Span) GetCode() bool {
	if x != nil {
		return x.Code
	}
	return false
}

func (x *Span) GetStrike() bool {
	if x != nil {
		return x.Strike
	}
	return false
}

func (x *Span) GetUnderline() bool {
	if x != nil {
		return x.Underline
	}
	return false
}

func (x *Span) GetLink() bool {
	if x != nil {
		return x.Link
	}
	return false
}

func (x *Span) GetQuote() bool {
	if x != nil {
		return x.Quote
	}
	return false
}

func (x *Span) GetHeading() bool {
	if x != nil {
		return x.Heading
	}
	return false
}

func (x *Span) GetSpoiler() bool {
	if x != nil {
		return x.Spoiler
	}
	return false
}

func (x *Span) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Span) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

// Space is a Matrix space with its direct child rooms (domain.Space).
type Space struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Children []string               `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	// bridge is the network whose bridge created this space, empty for one a person made.
	Bridge string `protobuf:"bytes,4,opt,name=bridge,proto3" json:"bridge,omitempty"`
	// original marks a space some room names as its canonical parent — where that room
	// came from.
	Original bool `protobuf:"varint,5,opt,name=original,proto3" json:"original,omitempty"`
	// keeper is somebody other than you who is inside this space and inside your rooms at
	// large — a bridge, from the outside.
	Keeper        string `protobuf:"bytes,6,opt,name=keeper,proto3" json:"keeper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_backend_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *Space) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Space) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Space) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Space) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

func (x *Space) GetOriginal() bool {
	if x != nil {
		return x.Original
	}
	return false
}

func (x *Space) GetKeeper() string {
	if x != nil {
		return x.Keeper
	}
	return ""
}

// Unread is one room's unread state (domain.Unread).
type Unread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Notifications int64                  `protobuf:"varint,2,opt,name=notifications,proto3" json:"notifications,omitempty"`
	Highlights    int64                  `protobuf:"varint,3,opt,name=highlights,proto3" json:"highlights,omitempty"`
	ReadEvent     string                 `protobuf:"bytes,4,opt,name=read_event,json=readEvent,proto3" json:"read_event,omitempty"`
	Messages      int64                  `protobuf:"varint,5,opt,name=messages,proto3" json:"messages,omitempty"` // cached messages after our receipts that are neither ours nor redacted
	Mentions      int64                  `protobuf:"varint,6,opt,name=mentions,proto3" json:"mentions,omitempty"` // the subset of messages that name us
	Counted       bool                   `protobuf:"varint,7,opt,name=counted,proto3" json:"counted,omitempty"`   // the cache could answer at all; false means fall back to notifications
	// threads is the per-thread breakdown, newest unread reply first.
	Threads []*ThreadUnread `protobuf:"bytes,8,rep,name=threads,proto3" json:"threads,omitempty"`
	// marked is MSC2867's m.marked_unread.
	Marked        bool `protobuf:"varint,9,opt,name=marked,proto3" json:"marked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unread) Reset() {
	*x = Unread{}
	mi := &file_backend_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unread) ProtoMessage() {}

func (x *Unread) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unread.ProtoReflect.Descriptor instead.
func (*Unread) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *Unread) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Unread) GetNotifications() int64 {
	if x != nil {
		return x.Notifications
	}
	return 0
}

func (x *Unread) GetHighlights() int64 {
	if x != nil {
		return x.Highlights
	}
	return 0
}

func (x *Unread) GetReadEvent() string {
	if x != nil {
		return x.ReadEvent
	}
	return ""
}

func (x *Unread) GetMessages() int64 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *Unread) GetMentions() int64 {
	if x != nil {
		return x.Mentions
	}
	return 0
}

func (x *Unread) GetCounted() bool {
	if x != nil {
		return x.Counted
	}
	return false
}

func (x *Unread) GetThreads() []*ThreadUnread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *Unread) GetMarked() bool {
	if x != nil {
		return x.Marked
	}
	return false
}

// ThreadUnread is one thread's share of a room's unread (domain.ThreadUnread), counted
// against that thread's own read receipt rather than the room's.
type ThreadUnread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          string                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Unread        int64                  `protobuf:"varint,2,opt,name=unread,proto3" json:"unread,omitempty"`
	Mentions      int64                  `protobuf:"varint,3,opt,name=mentions,proto3" json:"mentions,omitempty"`
	LatestAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=latest_at,json=latestAt,proto3" json:"latest_at,omitempty"`
	Latest        string                 `protobuf:"bytes,5,opt,name=latest,proto3" json:"latest,omitempty"` // the newest unread reply — what a receipt for this thread points at
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`   // the root's text, for a row in a room nothing has opened
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadUnread) Reset() {
	*x = ThreadUnread{}
	mi := &file_backend_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadUnread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadUnread) ProtoMessage() {}

func (x *ThreadUnread) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadUnread.ProtoReflect.Descriptor instead.
func (*ThreadUnread) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *ThreadUnread) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ThreadUnread) GetUnread() int64 {
	if x != nil {
		return x.Unread
	}
	return 0
}

func (x *ThreadUnread) GetMentions() int64 {
	if x != nil {
		return x.Mentions
	}
	return 0
}

func (x *ThreadUnread) GetLatestAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestAt
	}
	return nil
}

func (x *ThreadUnread) GetLatest() string {
	if x != nil {
		return x.Latest
	}
	return ""
}

func (x *ThreadUnread) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// Thread is one thread's summary (domain.Thread).
type Thread struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Root             string                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	RoomId           string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Count            int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // replies, excluding the root
	Latest           string                 `protobuf:"bytes,4,opt,name=latest,proto3" json:"latest,omitempty"`
	LatestAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=latest_at,json=latestAt,proto3" json:"latest_at,omitempty"`
	LatestSender     string                 `protobuf:"bytes,6,opt,name=latest_sender,json=latestSender,proto3" json:"latest_sender,omitempty"`
	LatestSenderName string                 `protobuf:"bytes,7,opt,name=latest_sender_name,json=latestSenderName,proto3" json:"latest_sender_name,omitempty"`
	Anchor           string                 `protobuf:"bytes,8,opt,name=anchor,proto3" json:"anchor,omitempty"`
	RootLoaded       bool                   `protobuf:"varint,9,opt,name=root_loaded,json=rootLoaded,proto3" json:"root_loaded,omitempty"`
	Unread           int64                  `protobuf:"varint,10,opt,name=unread,proto3" json:"unread,omitempty"`
	Mentions         int64                  `protobuf:"varint,11,opt,name=mentions,proto3" json:"mentions,omitempty"`
	Title            string                 `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"` // the root's text, for naming the thread where the root is not on screen
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Thread) Reset() {
	*x = Thread{}
	mi := &file_backend_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread) ProtoMessage() {}

func (x *Thread) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread.ProtoReflect.Descriptor instead.
func (*Thread) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *Thread) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *Thread) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Thread) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Thread) GetLatest() string {
	if x != nil {
		return x.Latest
	}
	return ""
}

func (x *Thread) GetLatestAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestAt
	}
	return nil
}

func (x *Thread) GetLatestSender() string {
	if x != nil {
		return x.LatestSender
	}
	return ""
}

func (x *Thread) GetLatestSenderName() string {
	if x != nil {
		return x.LatestSenderName
	}
	return ""
}

func (x *Thread) GetAnchor() string {
	if x != nil {
		return x.Anchor
	}
	return ""
}

func (x *Thread) GetRootLoaded() bool {
	if x != nil {
		return x.RootLoaded
	}
	return false
}

func (x *Thread) GetUnread() int64 {
	if x != nil {
		return x.Unread
	}
	return 0
}

func (x *Thread) GetMentions() int64 {
	if x != nil {
		return x.Mentions
	}
	return 0
}

func (x *Thread) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// Reaction is one m.annotation event (domain.Reaction).
type Reaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // the m.reaction event's own ID
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // the message this annotates
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"` // the reaction key, typically an emoji
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_backend_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *Reaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reaction) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Reaction) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Reaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Reaction) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// ReactionUpdate is one reaction arriving or going away (domain.ReactionUpdate).
type ReactionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reaction      *Reaction              `protobuf:"bytes,1,opt,name=reaction,proto3" json:"reaction,omitempty"`
	Removed       bool                   `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionUpdate) Reset() {
	*x = ReactionUpdate{}
	mi := &file_backend_v1_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionUpdate) ProtoMessage() {}

func (x *ReactionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionUpdate.ProtoReflect.Descriptor instead.
func (*ReactionUpdate) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *ReactionUpdate) GetReaction() *Reaction {
	if x != nil {
		return x.Reaction
	}
	return nil
}

func (x *ReactionUpdate) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// TimelinePage is one page of scrollback, oldest→newest, with the reactions discovered
// in it (domain.TimelinePage).
type TimelinePage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Reactions     []*Reaction            `protobuf:"bytes,2,rep,name=reactions,proto3" json:"reactions,omitempty"`
	Next          string                 `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelinePage) Reset() {
	*x = TimelinePage{}
	mi := &file_backend_v1_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelinePage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelinePage) ProtoMessage() {}

func (x *TimelinePage) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelinePage.ProtoReflect.Descriptor instead.
func (*TimelinePage) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{17}
}

func (x *TimelinePage) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *TimelinePage) GetReactions() []*Reaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *TimelinePage) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

// Draft is an outgoing message before it is sent (domain.Draft).
type Draft struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Body     string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Mentions []*Mention             `protobuf:"bytes,2,rep,name=mentions,proto3" json:"mentions,omitempty"`
	ReplyTo  string                 `protobuf:"bytes,3,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// Send the body as an m.emote rather than an m.text.
	Emote bool `protobuf:"varint,5,opt,name=emote,proto3" json:"emote,omitempty"`
	// The message this replaces (an m.replace).
	Edits string `protobuf:"bytes,6,opt,name=edits,proto3" json:"edits,omitempty"`
	// The thread to send into, empty for the main timeline.
	ThreadRoot string `protobuf:"bytes,4,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	// txn_id identifies the send, so sending it twice delivers it once.
	TxnId string `protobuf:"bytes,7,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	// Send the body exactly as typed, with no Markdown rendering.
	Plain         bool `protobuf:"varint,8,opt,name=plain,proto3" json:"plain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Draft) Reset() {
	*x = Draft{}
	mi := &file_backend_v1_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Draft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Draft) ProtoMessage() {}

func (x *Draft) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Draft.ProtoReflect.Descriptor instead.
func (*Draft) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{18}
}

func (x *Draft) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Draft) GetMentions() []*Mention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *Draft) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *Draft) GetEmote() bool {
	if x != nil {
		return x.Emote
	}
	return false
}

func (x *Draft) GetEdits() string {
	if x != nil {
		return x.Edits
	}
	return ""
}

func (x *Draft) GetThreadRoot() string {
	if x != nil {
		return x.ThreadRoot
	}
	return ""
}

func (x *Draft) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *Draft) GetPlain() bool {
	if x != nil {
		return x.Plain
	}
	return false
}

// Member is one person in a room (domain.Member).
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_backend_v1_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{19}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// SearchHit is one message matching a search (domain.SearchHit).
type SearchHit struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RoomId     string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EventId    string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sender     string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderName string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Snippet    string                 `protobuf:"bytes,6,opt,name=snippet,proto3" json:"snippet,omitempty"`
	// The attachment's name when the message carries one, empty otherwise.
	FileName string `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// The tracked entry this hit matched, for the tracked list and empty for every other
	// kind — the entry as configured rather than the text that matched it, because the
	// list groups by what the user wrote.
	Word string `protobuf:"bytes,8,opt,name=word,proto3" json:"word,omitempty"`
	// The people the message mentions (domain.SearchHit.Mentions).
	Mentions      []*Mention `protobuf:"bytes,9,rep,name=mentions,proto3" json:"mentions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_backend_v1_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{20}
}

func (x *SearchHit) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SearchHit) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SearchHit) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SearchHit) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *SearchHit) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SearchHit) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *SearchHit) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SearchHit) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *SearchHit) GetMentions() []*Mention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

// SASEmoji is one emoji of a short authentication string (domain.SASEmoji).
type SASEmoji struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Glyph         string                 `protobuf:"bytes,1,opt,name=glyph,proto3" json:"glyph,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SASEmoji) Reset() {
	*x = SASEmoji{}
	mi := &file_backend_v1_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SASEmoji) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SASEmoji) ProtoMessage() {}

func (x *SASEmoji) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SASEmoji.ProtoReflect.Descriptor instead.
func (*SASEmoji) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{21}
}

func (x *SASEmoji) GetGlyph() string {
	if x != nil {
		return x.Glyph
	}
	return ""
}

func (x *SASEmoji) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Verification is one step of an interactive SAS device-verification flow
// (domain.Verification).
type Verification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          VerificationKind       `protobuf:"varint,1,opt,name=kind,proto3,enum=backend.v1.VerificationKind" json:"kind,omitempty"`
	TxnId         string                 `protobuf:"bytes,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`     // requested: who is asking
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"` // requested: which device
	Emojis        []*SASEmoji            `protobuf:"bytes,5,rep,name=emojis,proto3" json:"emojis,omitempty"`
	Decimals      []int64                `protobuf:"varint,6,rep,packed,name=decimals,proto3" json:"decimals,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"` // canceled: why; restored: what was imported
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verification) Reset() {
	*x = Verification{}
	mi := &file_backend_v1_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verification) ProtoMessage() {}

func (x *Verification) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verification.ProtoReflect.Descriptor instead.
func (*Verification) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{22}
}

func (x *Verification) GetKind() VerificationKind {
	if x != nil {
		return x.Kind
	}
	return VerificationKind_VERIFICATION_KIND_UNSPECIFIED
}

func (x *Verification) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *Verification) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Verification) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Verification) GetEmojis() []*SASEmoji {
	if x != nil {
		return x.Emojis
	}
	return nil
}

func (x *Verification) GetDecimals() []int64 {
	if x != nil {
		return x.Decimals
	}
	return nil
}

func (x *Verification) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// TempRule is one temporary notification rule in force — what do-not-disturb is made of
// (notify.Rule with Temp set).
type TempRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is how to say it — "Standup", "Alice", "all notifications".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// match names a place.
	Match string `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	// sender narrows it to one person's MXID.
	Sender string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	// show and ring are the bars for a popup and a sound; UNSPECIFIED leaves the axis alone.
	Show Level `protobuf:"varint,4,opt,name=show,proto3,enum=backend.v1.Level" json:"show,omitempty"`
	Ring Level `protobuf:"varint,5,opt,name=ring,proto3,enum=backend.v1.Level" json:"ring,omitempty"`
	// until is when it lapses.
	Until         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempRule) Reset() {
	*x = TempRule{}
	mi := &file_backend_v1_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempRule) ProtoMessage() {}

func (x *TempRule) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempRule.ProtoReflect.Descriptor instead.
func (*TempRule) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{23}
}

func (x *TempRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TempRule) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *TempRule) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TempRule) GetShow() Level {
	if x != nil {
		return x.Show
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *TempRule) GetRing() Level {
	if x != nil {
		return x.Ring
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *TempRule) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

var File_backend_v1_types_proto protoreflect.FileDescriptor

const file_backend_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x16backend/v1/types.proto\x12\n" +
	"backend.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_direct\x18\x03 \x01(\bR\bisDirect\x12\x18\n" +
	"\amembers\x18\x04 \x03(\tR\amembers\x12\x1e\n" +
	"\n" +
	"membership\x18\x05 \x01(\tR\n" +
	"membership\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x06 \x01(\tR\tinvitedBy\x12 \n" +
	"\vreplacement\x18\a \x01(\tR\vreplacement\x12\x14\n" +
	"\x05topic\x18\b \x01(\tR\x05topic\x12\x1a\n" +
	"\barchived\x18\t \x01(\bR\barchived\x12\x14\n" +
	"\x05forum\x18\n" +
	" \x01(\bR\x05forum\"e\n" +
	"\aMention\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05known\x18\x04 \x01(\tR\x05known\"\x85\x01\n" +
	"\x05Media\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x03R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x03R\x06height\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\"\x95\x01\n" +
	"\bRevision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12*\n" +
	"\x02at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12-\n" +
	"\x06format\x18\x05 \x01(\v2\x15.backend.v1.FormattedR\x06formatJ\x04\b\x03\x10\x04R\x04html\";\n" +
	"\bActivity\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06typing\x18\x02 \x03(\tR\x06typing\"\xad\x06\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bredacted\x18\a \x01(\bR\bredacted\x12\x16\n" +
	"\x06edited\x18\b \x01(\bR\x06edited\x12\x19\n" +
	"\breply_to\x18\t \x01(\tR\areplyTo\x12\x1c\n" +
	"\tmentioned\x18\n" +
	" \x01(\bR\tmentioned\x12'\n" +
	"\x05media\x18\v \x01(\v2\x11.backend.v1.MediaR\x05media\x12/\n" +
	"\bmentions\x18\f \x03(\v2\x13.backend.v1.MentionR\bmentions\x12\x14\n" +
	"\x05emote\x18\x0e \x01(\bR\x05emote\x12\x1f\n" +
	"\vthread_root\x18\r \x01(\tR\n" +
	"threadRoot\x12\x1f\n" +
	"\vredacted_by\x18\x10 \x01(\tR\n" +
	"redactedBy\x12'\n" +
	"\x0fredacted_reason\x18\x11 \x01(\tR\x0eredactedReason\x12-\n" +
	"\x13redacted_at_unix_ms\x18\x12 \x01(\x03R\x10redactedAtUnixMs\x12)\n" +
	"\x11edited_at_unix_ms\x18\x13 \x01(\x03R\x0eeditedAtUnixMs\x12\x1f\n" +
	"\vrevision_id\x18\x14 \x01(\tR\n" +
	"revisionId\x12\x1a\n" +
	"\breverted\x18\x15 \x01(\bR\breverted\x12-\n" +
	"\x06format\x18\x16 \x01(\v2\x15.backend.v1.FormattedR\x06format\x12 \n" +
	"\vplaceholder\x18\x17 \x01(\bR\vplaceholder\x12$\n" +
	"\x04poll\x18\x18 \x01(\v2\x10.backend.v1.PollR\x04poll\x12\x10\n" +
	"\x03seq\x18\x19 \x01(\x03R\x03seqJ\x04\b\x0f\x10\x10R\x04html\"\xf2\x01\n" +
	"\x04Poll\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x120\n" +
	"\aoptions\x18\x03 \x03(\v2\x16.backend.v1.PollOptionR\aoptions\x12\x1a\n" +
	"\bmultiple\x18\x04 \x01(\bR\bmultiple\x12\x16\n" +
	"\x06closed\x18\x05 \x01(\bR\x06closed\x12\x12\n" +
	"\x04quiz\x18\x06 \x01(\bR\x04quiz\x12\x16\n" +
	"\x06voters\x18\a \x01(\x03R\x06voters\x12,\n" +
	"\aballots\x18\b \x03(\v2\x12.backend.v1.BallotR\aballots\"8\n" +
	"\x06Ballot\x12\x14\n" +
	"\x05voter\x18\x01 \x01(\tR\x05voter\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\"Z\n" +
	"\n" +
	"PollOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05votes\x18\x03 \x01(\x03R\x05votes\x12\x12\n" +
	"\x04mine\x18\x04 \x01(\bR\x04mine\"G\n" +
	"\tFormatted\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12&\n" +
	"\x05spans\x18\x02 \x03(\v2\x10.backend.v1.SpanR\x05spans\"\xae\x02\n" +
	"\x04Span\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\x12\x12\n" +
	"\x04bold\x18\x03 \x01(\bR\x04bold\x12\x16\n" +
	"\x06italic\x18\x04 \x01(\bR\x06italic\x12\x12\n" +
	"\x04code\x18\x05 \x01(\bR\x04code\x12\x16\n" +
	"\x06strike\x18\x06 \x01(\bR\x06strike\x12\x1c\n" +
	"\tunderline\x18\a \x01(\bR\tunderline\x12\x12\n" +
	"\x04link\x18\b \x01(\bR\x04link\x12\x14\n" +
	"\x05quote\x18\t \x01(\bR\x05quote\x12\x18\n" +
	"\aheading\x18\n" +
	" \x01(\bR\aheading\x12\x18\n" +
	"\aspoiler\x18\v \x01(\bR\aspoiler\x12\x16\n" +
	"\x06reason\x18\f \x01(\tR\x06reason\x12\x12\n" +
	"\x04href\x18\r \x01(\tR\x04href\"\x93\x01\n" +
	"\x05Space\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bchildren\x18\x03 \x03(\tR\bchildren\x12\x16\n" +
	"\x06bridge\x18\x04 \x01(\tR\x06bridge\x12\x1a\n" +
	"\boriginal\x18\x05 \x01(\bR\boriginal\x12\x16\n" +
	"\x06keeper\x18\x06 \x01(\tR\x06keeper\"\xa4\x02\n" +
	"\x06Unread\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12$\n" +
	"\rnotifications\x18\x02 \x01(\x03R\rnotifications\x12\x1e\n" +
	"\n" +
	"highlights\x18\x03 \x01(\x03R\n" +
	"highlights\x12\x1d\n" +
	"\n" +
	"read_event\x18\x04 \x01(\tR\treadEvent\x12\x1a\n" +
	"\bmessages\x18\x05 \x01(\x03R\bmessages\x12\x1a\n" +
	"\bmentions\x18\x06 \x01(\x03R\bmentions\x12\x18\n" +
	"\acounted\x18\a \x01(\bR\acounted\x122\n" +
	"\athreads\x18\b \x03(\v2\x18.backend.v1.ThreadUnreadR\athreads\x12\x16\n" +
	"\x06marked\x18\t \x01(\bR\x06marked\"\xbd\x01\n" +
	"\fThreadUnread\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12\x16\n" +
	"\x06unread\x18\x02 \x01(\x03R\x06unread\x12\x1a\n" +
	"\bmentions\x18\x03 \x01(\x03R\bmentions\x127\n" +
	"\tlatest_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blatestAt\x12\x16\n" +
	"\x06latest\x18\x05 \x01(\tR\x06latest\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\"\xf2\x02\n" +
	"\x06Thread\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x16\n" +
	"\x06latest\x18\x04 \x01(\tR\x06latest\x127\n" +
	"\tlatest_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blatestAt\x12#\n" +
	"\rlatest_sender\x18\x06 \x01(\tR\flatestSender\x12,\n" +
	"\x12latest_sender_name\x18\a \x01(\tR\x10latestSenderName\x12\x16\n" +
	"\x06anchor\x18\b \x01(\tR\x06anchor\x12\x1f\n" +
	"\vroot_loaded\x18\t \x01(\bR\n" +
	"rootLoaded\x12\x16\n" +
	"\x06unread\x18\n" +
	" \x01(\x03R\x06unread\x12\x1a\n" +
	"\bmentions\x18\v \x01(\x03R\bmentions\x12\x14\n" +
	"\x05title\x18\f \x01(\tR\x05title\"u\n" +
	"\bReaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\"\\\n" +
	"\x0eReactionUpdate\x120\n" +
	"\breaction\x18\x01 \x01(\v2\x14.backend.v1.ReactionR\breaction\x12\x18\n" +
	"\aremoved\x18\x02 \x01(\bR\aremoved\"\x87\x01\n" +
	"\fTimelinePage\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.backend.v1.MessageR\bmessages\x122\n" +
	"\treactions\x18\x02 \x03(\v2\x14.backend.v1.ReactionR\treactions\x12\x12\n" +
	"\x04next\x18\x03 \x01(\tR\x04next\"\xe1\x01\n" +
	"\x05Draft\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12/\n" +
	"\bmentions\x18\x02 \x03(\v2\x13.backend.v1.MentionR\bmentions\x12\x19\n" +
	"\breply_to\x18\x03 \x01(\tR\areplyTo\x12\x14\n" +
	"\x05emote\x18\x05 \x01(\bR\x05emote\x12\x14\n" +
	"\x05edits\x18\x06 \x01(\tR\x05edits\x12\x1f\n" +
	"\vthread_root\x18\x04 \x01(\tR\n" +
	"threadRoot\x12\x15\n" +
	"\x06txn_id\x18\a \x01(\tR\x05txnId\x12\x14\n" +
	"\x05plain\x18\b \x01(\bR\x05plain\"D\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"\xae\x02\n" +
	"\tSearchHit\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\asnippet\x18\x06 \x01(\tR\asnippet\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\x12\x12\n" +
	"\x04word\x18\b \x01(\tR\x04word\x12/\n" +
	"\bmentions\x18\t \x03(\v2\x13.backend.v1.MentionR\bmentions\"4\n" +
	"\bSASEmoji\x12\x14\n" +
	"\x05glyph\x18\x01 \x01(\tR\x05glyph\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe5\x01\n" +
	"\fVerification\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.backend.v1.VerificationKindR\x04kind\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\tR\x05txnId\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12,\n" +
	"\x06emojis\x18\x05 \x03(\v2\x14.backend.v1.SASEmojiR\x06emojis\x12\x1a\n" +
	"\bdecimals\x18\x06 \x03(\x03R\bdecimals\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"\xcc\x01\n" +
	"\bTempRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05match\x18\x02 \x01(\tR\x05match\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12%\n" +
	"\x04show\x18\x04 \x01(\x0e2\x11.backend.v1.LevelR\x04show\x12%\n" +
	"\x04ring\x18\x05 \x01(\x0e2\x11.backend.v1.LevelR\x04ring\x120\n" +
	"\x05until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05until*\xcd\x01\n" +
	"\x10VerificationKind\x12!\n" +
	"\x1dVERIFICATION_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bVERIFICATION_KIND_REQUESTED\x10\x01\x12\x19\n" +
	"\x15VERIFICATION_KIND_SAS\x10\x02\x12\x1a\n" +
	"\x16VERIFICATION_KIND_DONE\x10\x03\x12\x1e\n" +
	"\x1aVERIFICATION_KIND_CANCELED\x10\x04\x12\x1e\n" +
	"\x1aVERIFICATION_KIND_RESTORED\x10\x05*^\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"LEVEL_NONE\x10\x01\x12\x11\n" +
	"\rLEVEL_MENTION\x10\x02\x12\f\n" +
	"\bLEVEL_DM\x10\x03\x12\r\n" +
	"\tLEVEL_ALL\x10\x04B@Z>github.com/EugeneShtoka/kith/internal/api/backend/v1;backendv1b\x06proto3"

var (
	file_backend_v1_types_proto_rawDescOnce sync.Once
	file_backend_v1_types_proto_rawDescData []byte
)

func file_backend_v1_types_proto_rawDescGZIP() []byte {
	file_backend_v1_types_proto_rawDescOnce.Do(func() {
		file_backend_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_v1_types_proto_rawDesc), len(file_backend_v1_types_proto_rawDesc)))
	})
	return file_backend_v1_types_proto_rawDescData
}

var file_backend_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_backend_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_backend_v1_types_proto_goTypes = []any{
	(VerificationKind)(0),         // 0: backend.v1.VerificationKind
	(Level)(0),                    // 1: backend.v1.Level
	(*Room)(nil),                  // 2: backend.v1.Room
	(*Mention)(nil),               // 3: backend.v1.Mention
	(*Media)(nil),                 // 4: backend.v1.Media
	(*Revision)(nil),              // 5: backend.v1.Revision
	(*Activity)(nil),              // 6: backend.v1.Activity
	(*Message)(nil),               // 7: backend.v1.Message
	(*Poll)(nil),                  // 8: backend.v1.Poll
	(*Ballot)(nil),                // 9: backend.v1.Ballot
	(*PollOption)(nil),            // 10: backend.v1.PollOption
	(*Formatted)(nil),             // 11: backend.v1.Formatted
	(*Span)(nil),                  // 12: backend.v1.Span
	(*Space)(nil),                 // 13: backend.v1.Space
	(*Unread)(nil),                // 14: backend.v1.Unread
	(*ThreadUnread)(nil),          // 15: backend.v1.ThreadUnread
	(*Thread)(nil),                // 16: backend.v1.Thread
	(*Reaction)(nil),              // 17: backend.v1.Reaction
	(*ReactionUpdate)(nil),        // 18: backend.v1.ReactionUpdate
	(*TimelinePage)(nil),          // 19: backend.v1.TimelinePage
	(*Draft)(nil),                 // 20: backend.v1.Draft
	(*Member)(nil),                // 21: backend.v1.Member
	(*SearchHit)(nil),             // 22: backend.v1.SearchHit
	(*SASEmoji)(nil),              // 23: backend.v1.SASEmoji
	(*Verification)(nil),          // 24: backend.v1.Verification
	(*TempRule)(nil),              // 25: backend.v1.TempRule
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
}
var file_backend_v1_types_proto_depIdxs = []int32{
	26, // 0: backend.v1.Revision.at:type_name -> google.protobuf.Timestamp
	11, // 1: backend.v1.Revision.format:type_name -> backend.v1.Formatted
	26, // 2: backend.v1.Message.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 3: backend.v1.Message.media:type_name -> backend.v1.Media
	3,  // 4: backend.v1.Message.mentions:type_name -> backend.v1.Mention
	11, // 5: backend.v1.Message.format:type_name -> backend.v1.Formatted
	8,  // 6: backend.v1.Message.poll:type_name -> backend.v1.Poll
	10, // 7: backend.v1.Poll.options:type_name -> backend.v1.PollOption
	9,  // 8: backend.v1.Poll.ballots:type_name -> backend.v1.Ballot
	12, // 9: backend.v1.Formatted.spans:type_name -> backend.v1.Span
	15, // 10: backend.v1.Unread.threads:type_name -> backend.v1.ThreadUnread
	26, // 11: backend.v1.ThreadUnread.latest_at:type_name -> google.protobuf.Timestamp
	26, // 12: backend.v1.Thread.latest_at:type_name -> google.protobuf.Timestamp
	17, // 13: backend.v1.ReactionUpdate.reaction:type_name -> backend.v1.Reaction
	7,  // 14: backend.v1.TimelinePage.messages:type_name -> backend.v1.Message
	17, // 15: backend.v1.TimelinePage.reactions:type_name -> backend.v1.Reaction
	3,  // 16: backend.v1.Draft.mentions:type_name -> backend.v1.Mention
	26, // 17: backend.v1.SearchHit.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 18: backend.v1.SearchHit.mentions:type_name -> backend.v1.Mention
	0,  // 19: backend.v1.Verification.kind:type_name -> backend.v1.VerificationKind
	23, // 20: backend.v1.Verification.emojis:type_name -> backend.v1.SASEmoji
	1,  // 21: backend.v1.TempRule.show:type_name -> backend.v1.Level
	1,  // 22: backend.v1.TempRule.ring:type_name -> backend.v1.Level
	26, // 23: backend.v1.TempRule.until:type_name -> google.protobuf.Timestamp
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_backend_v1_types_proto_init() }
func file_backend_v1_types_proto_init() {
	if File_backend_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_v1_types_proto_rawDesc), len(file_backend_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_v1_types_proto_goTypes,
		DependencyIndexes: file_backend_v1_types_proto_depIdxs,
		EnumInfos:         file_backend_v1_types_proto_enumTypes,
		MessageInfos:      file_backend_v1_types_proto_msgTypes,
	}.Build()
	File_backend_v1_types_proto = out.File
	file_backend_v1_types_proto_goTypes = nil
	file_backend_v1_types_proto_depIdxs = nil
}
