#!/usr/bin/env python3
"""Regenerate internal/spell/frequencies_generated.go (`make freq-manifest`).

Pinned word-frequency lists (with SHA-256) for the rare-word check: some dictionaries
(e.g. Hspell) accept almost any string. Prunes exactly as the installer does
(MIN_COUNT, `<word> <count>` lines) so recorded sizes are true; the Go side reads the
threshold from the generated file. Downloads ~180 MB.
"""

import hashlib
import sys
import urllib.request

# Bumping the pin is deliberate: re-run and review the diff. (Fixed corpus; upstream is static.)
COMMIT = "525f9b560de45753a5ea01069454e72e9aa541c6"
COMMIT_DATE = "2022-02-07"

REPO = "hermitdave/FrequencyWords"
RAW = f"https://raw.githubusercontent.com/{REPO}/{COMMIT}/"

# Entries seen fewer than this many times are dropped on install.
# Kept low: the rule reads the rare end too, and real words sit at counts of 6-19.
MIN_COUNT = 3

# The dictionary tag this list is for -> the language directory upstream keeps it in.
# (en_US and en_GB share one list; pt_BR has its own.)
SOURCES = {
    "en_US": "en",
    "en_GB": "en",
    "he_IL": "he",
    "ru_RU": "ru",
    "uk_UA": "uk",
    "de_DE": "de",
    "fr_FR": "fr",
    "es_ES": "es",
    "it_IT": "it",
    "pt_BR": "pt_br",
    "nl_NL": "nl",
    "pl_PL": "pl",
}

# Upstream README states the lists' license (LICENSE covers only the generator).
LICENSE = "LICENSE"

OUT = "internal/spell/frequencies_generated.go"


def fetch(path):
    """Download one file from the pinned commit and return its bytes."""
    with urllib.request.urlopen(RAW + path, timeout=300) as r:  # noqa: S310 - fixed https host
        return r.read()


def measure(blob):
    """Count what survives pruning, and what it costs written out.

    This is the installer's rule, spelled the same way: split on whitespace, expect a
    word and a count, drop anything else, keep counts at or above the threshold. The
    byte figure is the body the installer writes — `<word> <count>\\n` — and excludes
    the header it puts in front, which is a fixed few hundred bytes and would only make
    the number harder to compare against a re-run.
    """
    words = 0
    body = 0
    total = 0
    for line in blob.decode("utf-8").splitlines():
        parts = line.split()
        if len(parts) != 2 or not parts[1].isdigit():
            continue
        total += 1
        count = int(parts[1])
        if count < MIN_COUNT:
            continue
        words += 1
        body += len(parts[0].encode("utf-8")) + 1 + len(parts[1]) + 1
    return words, body, total


def main():
    lic_blob = fetch(LICENSE)
    lic = (LICENSE, hashlib.sha256(lic_blob).hexdigest(), len(lic_blob))

    # One download per language, not per tag: en_US and en_GB are the same file, and
    # hashing it twice would only prove the network is deterministic.
    seen = {}
    entries = []
    for tag, lang in sorted(SOURCES.items()):
        path = f"content/2018/{lang}/{lang}_full.txt"
        if lang not in seen:
            blob = fetch(path)
            words, body, total = measure(blob)
            seen[lang] = (hashlib.sha256(blob).hexdigest(), len(blob), words, body)
            print(
                f"  {path}  {len(blob):>12,} bytes  "
                f"{words:>9,} of {total:,} kept  {body:>12,} bytes on disk",
                file=sys.stderr,
            )
        digest, size, words, body = seen[lang]
        entries.append((tag, lang, path, digest, size, words, body))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(render(entries, lic))
    print(f"wrote {OUT} with {len(entries)} lists", file=sys.stderr)


def render(entries, lic):
    rows = "\n".join(
        f'\t"{tag}": {{\n'
        f'\t\tTag:   "{tag}",\n'
        f'\t\tLang:  "{lang}",\n'
        f'\t\tList:  File{{Path: "{path}", SHA256: "{digest}", Size: {size}}},\n'
        f"\t\tWords: {words},\n"
        f"\t\tKept:  {body},\n"
        f"\t}},"
        for tag, lang, path, digest, size, words, body in entries
    )
    lic_path, lic_digest, lic_size = lic
    return f'''// Code generated by scripts/gen-freq-manifest.py. DO NOT EDIT.

package spell

// The frequency lists kith can install, pinned to one upstream commit.
//
// A SHA-256 mismatch is a refusal (see frequency.go). Regenerate with `make freq-manifest`.

// frequencyRepo and frequencyCommit are the source and the pin.
const (
	frequencyRepo   = "{REPO}"
	frequencyCommit = "{COMMIT}"
	frequencyDate   = "{COMMIT_DATE}"
	frequencyBase   = "https://raw.githubusercontent.com/{REPO}/{COMMIT}/"
)

// frequencyMinCount is how often a word must appear upstream to be kept on install.
// It lives here because the recorded Words/Kept figures are measured with it.
const frequencyMinCount = {MIN_COUNT}

// frequencyLicense is upstream's license file, installed beside every list.
var frequencyLicense = File{{Path: "{lic_path}", SHA256: "{lic_digest}", Size: {lic_size}}}

// frequencySources is every installable frequency list, by dictionary tag (e.g. he_IL).
var frequencySources = map[string]FreqSource{{
{rows}
}}
'''


if __name__ == "__main__":
    main()
