#!/usr/bin/env python3
"""Regenerate internal/llamacpp/models/models_generated.go (`make model-manifest`).

Pins the completion model to one revision with its SHA-256, taken from the HuggingFace
LFS API — no download needed.
"""

import json
import sys
import urllib.request

# Bumping the pin is deliberate: re-run and review the diff.
REPO = "HuggingFaceTB/SmolLM2-360M-Instruct-GGUF"
COMMIT = "593b5a2e04c8f3e4ee880263f93e0bd2901ad47f"
COMMIT_DATE = "2024-10-31"

API = f"https://huggingface.co/api/models/{REPO}?blobs=true&revision={COMMIT}"
RESOLVE = f"https://huggingface.co/{REPO}/resolve/{COMMIT}/"

# tag -> (upstream filename, human name, license, measured recall@4).
# recall@4 is measured offline (542 probes from the account's own messages).
SOURCES = {
    "smollm2-360m": (
        "smollm2-360m-instruct-q8_0.gguf",
        "SmolLM2 360M Instruct (Q8_0)",
        "Apache-2.0",
        0.339,
    ),
}

HEADER = '''// Code generated by scripts/gen-model-manifest.py. DO NOT EDIT.

package models

// The models kith can install, pinned to one upstream revision.
//
// A SHA-256 mismatch is a refusal (see install.go). Regenerate with `make model-manifest`.

// The source and the pin.
const (
\tmodelRepo   = "{repo}"
\tmodelCommit = "{commit}"
\tmodelDate   = "{date}"
\tmodelBase   = "{base}"
)

// modelSources is every model that can be installed, by the tag it installs as.
var modelSources = map[string]Source{{
'''


def main() -> int:
    with urllib.request.urlopen(API) as response:
        meta = json.load(response)
    if meta.get("sha") != COMMIT:
        print(f"upstream HEAD is {meta.get('sha')}, not the pinned {COMMIT}", file=sys.stderr)
        # Not fatal: the resolve URLs name the commit, so the pin still describes exactly
        # what will be fetched. It is worth saying out loud that upstream has moved on.

    blobs = {f["rfilename"]: f for f in meta.get("siblings", [])}
    out = [HEADER.format(repo=REPO, commit=COMMIT, date=COMMIT_DATE, base=RESOLVE)]
    for tag in sorted(SOURCES):
        path, name, license_name, recall = SOURCES[tag]
        blob = blobs.get(path)
        if blob is None:
            print(f"{path} is not in {REPO} at {COMMIT}", file=sys.stderr)
            return 1
        lfs = blob.get("lfs")
        if not lfs or not lfs.get("sha256"):
            # A file stored inline rather than in LFS has no recorded hash, and hashing it
            # would mean downloading it. Refusing beats shipping an entry with no pin.
            print(f"{path} has no recorded LFS sha256 — refusing to pin it", file=sys.stderr)
            return 1
        out.append(f'\t"{tag}": {{\n')
        out.append(f'\t\tTag:     "{tag}",\n')
        out.append(f'\t\tName:    "{name}",\n')
        out.append(
            f'\t\tFile:    File{{Path: "{path}", '
            f'SHA256: "{lfs["sha256"]}", Size: {lfs["size"]}}},\n'
        )
        out.append(f"\t\tRecall:  {recall},\n")
        out.append(f'\t\tLicense: "{license_name}",\n')
        out.append("\t},\n")
    out.append("}\n")

    with open("internal/llamacpp/models/models_generated.go", "w", encoding="utf-8") as f:
        f.write("".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
