#!/usr/bin/env python3
"""Generate internal/emoji/generated.go from Unicode's emoji-test.txt (`make emoji`).

Standard: single-glyph, fully-qualified, no skin tone (kith applies tones).
Sequences: ZWJ sequences and flags — opt-in, since fonts without the ligature draw
them wider than measured. Shortcodes come from CLDR names; emoji.go's names win.
"""

from __future__ import annotations

import re
import sys
import unicodedata
import urllib.request
from pathlib import Path

SOURCE = "https://unicode.org/Public/emoji/latest/emoji-test.txt"
OUT = Path(__file__).resolve().parent.parent / "internal" / "emoji" / "generated.go"

TONES = range(0x1F3FB, 0x1F400)
REGIONAL = range(0x1F1E6, 0x1F200)
ZWJ = 0x200D
KEYCAP = 0x20E3

# Newer emoji draw as 1-column tofu on lagging fonts, breaking layout. To raise it:
# bump, `make emoji`, then `go run ./cmd/emoji-probe -set complete` on your font.
MAX_EMOJI_VERSION = 15.1


def shortcode(name: str) -> str:
    """Turn a CLDR name into a typeable shortcode: lowercase words joined by _."""
    name = unicodedata.normalize("NFKD", name)
    name = name.replace("’", "").replace("“", "").replace("”", "")
    # "flag: Ukraine" and "keycap: #" both carry their distinguishing part after the
    # colon, so it is kept rather than dropped.
    words = re.split(r"[^0-9a-zA-Z]+", name.lower())
    return "_".join(w for w in words if w)


def classify(codepoints: list[int]) -> str:
    """Which tier a sequence belongs to, or "skip" for one we do not offer at all.

    Two whole classes are dropped, both because their *drawn* width is not the width
    anything measures them at — and a cell one column out wraps its row and shifts the
    pane (see cmd/emoji-probe):

      keycaps   `1️⃣` is base + VS16 + U+20E3 and measures two columns while terminals
                draw it in one. There are eleven of them and no way to reconcile it: the
                selector trick that fixes a text-presentation emoji cannot make a
                terminal draw *wider*.

      pre-toned every emoji here that already carries a Fitzpatrick modifier. For the
                single-glyph ones kith applies the tone itself from [display]
                skin_tone, so they are duplicates; for the ZWJ ones (⛹🏿‍♂️) they are
                both a fivefold multiplication of the set and — measured — the largest
                group that draws wider than it measures.
    """
    if KEYCAP in codepoints:
        return "skip"
    if any(cp in TONES for cp in codepoints):
        return "skip"
    if ZWJ in codepoints or any(cp in REGIONAL for cp in codepoints):
        return "sequence"
    return "standard"


def within_version(field: str) -> bool:
    """Whether an "E15.1" version field is one this generation includes."""
    try:
        return float(field.lstrip("Ee")) <= MAX_EMOJI_VERSION
    except ValueError:
        return False


def parse(text: str) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    standard: list[tuple[str, str]] = []
    sequence: list[tuple[str, str]] = []
    seen: set[str] = set()
    for line in text.splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        codes, rest = line.split(";", 1)
        status, _, comment = rest.partition("#")
        if status.strip() != "fully-qualified":
            continue
        codepoints = [int(c, 16) for c in codes.split()]
        glyph = "".join(chr(cp) for cp in codepoints)
        # The comment is "<glyph> E<version> <name>": the version gates it, the name
        # becomes the shortcode.
        parts = comment.strip().split(" ", 2)
        if len(parts) < 3:
            continue
        if not within_version(parts[1]):
            continue
        name = shortcode(parts[2])
        if not name or name in seen:
            continue
        seen.add(name)
        kind = classify(codepoints)
        if kind == "skip":
            continue
        if kind == "standard":
            standard.append((name, glyph))
        elif kind == "sequence":
            sequence.append((name, glyph))
    return standard, sequence


def render(standard, sequence) -> str:
    def table(varname: str, rows, doc: str) -> str:
        lines = [doc, f"var {varname} = map[string]string{{"]
        for name, glyph in rows:
            lines.append(f'\t{name!r}: {glyph!r},'.replace("'", '"'))
        lines.append("}")
        return "\n".join(lines)

    header = f"""// Code generated by scripts/gen-emoji.py from {SOURCE}. DO NOT EDIT.
//
// Regenerate with `make emoji` after a new Unicode release. The file is committed so
// that a build needs no network; the script is a development tool.

package emoji
"""
    return "\n".join(
        [
            header,
            table(
                "Standard",
                standard,
                "// Standard is every fully-qualified single-glyph emoji: no ZWJ sequence, no\n"
                "// flag, and no pre-applied skin tone (kith applies the tone itself).",
            ),
            "",
            table(
                "Sequences",
                sequence,
                "// Sequences is the composed emoji — ZWJ sequences and flags. They are kept\n"
                "// apart because they are the class fonts disagree about: without the ligature a\n"
                "// font draws the parts side by side, which is wider than the cell it was measured\n"
                "// into, and one column out wraps the row.",
            ),
            "",
        ]
    )


def main() -> int:
    src = sys.argv[1] if len(sys.argv) > 1 else SOURCE
    text = (
        Path(src).read_text(encoding="utf-8")
        if not src.startswith("http")
        else urllib.request.urlopen(src, timeout=30).read().decode("utf-8")  # noqa: S310
    )
    standard, sequence = parse(text)
    OUT.write_text(render(standard, sequence), encoding="utf-8")
    print(f"{OUT.name}: {len(standard)} standard, {len(sequence)} sequence emoji")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
