#!/usr/bin/env python3
"""Regenerate internal/spell/dictionaries_generated.go (`make dict-manifest`).

Pins LibreOffice/dictionaries to one commit and records each file's SHA-256, so the
installer refuses anything else. Downloads ~45 MB to hash.
"""

import hashlib
import json
import sys
import urllib.request

# Bumping the pin is deliberate: re-run and review the diff.
COMMIT = "32b006a2c22a4ac7e8ed3f03346f7b3d85a970a4"
COMMIT_DATE = "2026-08-22"

REPO = "LibreOffice/dictionaries"
RAW = f"https://raw.githubusercontent.com/{REPO}/{COMMIT}/"
TREE = f"https://api.github.com/repos/{REPO}/git/trees/{COMMIT}?recursive=1"

# tag (what users type and the install name) -> upstream basename, no extension.
SOURCES = {
    "en_US": "en/en_US",
    "en_GB": "en/en_GB",
    "he_IL": "he_IL/he_IL",
    "ru_RU": "ru_RU/ru_RU",
    "uk_UA": "uk_UA/uk_UA",
    "de_DE": "de/de_DE_frami",
    "fr_FR": "fr_FR/dictionaries/fr",
    "es_ES": "es/es_ES",
    "it_IT": "it_IT/it_IT",
    "pt_BR": "pt_BR/pt_BR",
    "nl_NL": "nl_NL/nl_NL",
    "pl_PL": "pl_PL/pl_PL",
}

OUT = "internal/spell/dictionaries_generated.go"


def fetch(path):
    """Download one file from the pinned commit and return its bytes."""
    with urllib.request.urlopen(RAW + path, timeout=120) as r:  # noqa: S310 - fixed https host
        return r.read()


def tree():
    """The repository's file list at the pinned commit."""
    with urllib.request.urlopen(TREE, timeout=120) as r:  # noqa: S310 - fixed https host
        return json.load(r)


def license_path(paths, base):
    """Find the license covering a dictionary.

    Upstream is not consistent about this — some directories carry a per-dictionary
    README, some one README for the lot, some only a COPYING. The order here is
    most-specific-first, because a per-dictionary README states the license *for that
    dictionary*, where a shared COPYING is the license of whatever else is in the
    folder as well.
    """
    directory = base.rsplit("/", 1)[0]
    name = base.rsplit("/", 1)[1]
    wanted = [
        f"{directory}/README_{name}.txt",
        f"{directory}/README.txt",
        f"{directory}/LICENSE",
        f"{directory}/LICENSES-en.txt",
        f"{directory}/COPYING",
    ]
    for candidate in wanted:
        if candidate in paths:
            return candidate
    # Anything that looks like one, deterministically chosen so a re-run does not
    # produce a different manifest from the same commit.
    for candidate in sorted(paths):
        if candidate.startswith(directory + "/") and (
            "COPYING" in candidate or "LICENSE" in candidate or "README" in candidate
        ):
            return candidate
    return ""


def main():
    paths = {e["path"] for e in tree()["tree"] if e["type"] == "blob"}

    entries = []
    for tag, base in sorted(SOURCES.items()):
        files = {}
        for ext in (".aff", ".dic"):
            path = base + ext
            if path not in paths:
                sys.exit(f"{tag}: {path} is not in the pinned commit")
            blob = fetch(path)
            files[ext] = (path, hashlib.sha256(blob).hexdigest(), len(blob))
            print(f"  {path}  {len(blob):>9,} bytes", file=sys.stderr)

        lic = license_path(paths, base)
        lic_entry = ("", "", 0)
        if lic:
            blob = fetch(lic)
            lic_entry = (lic, hashlib.sha256(blob).hexdigest(), len(blob))
        else:
            print(f"  {tag}: no license file found upstream", file=sys.stderr)

        entries.append((tag, files[".aff"], files[".dic"], lic_entry))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(render(entries))
    print(f"wrote {OUT} with {len(entries)} dictionaries", file=sys.stderr)


def go_file(v):
    # The type is spelled out: Go lets a *map or slice element* elide its literal type
    # but not a struct field, and these are struct fields.
    path, digest, size = v
    return f'File{{Path: "{path}", SHA256: "{digest}", Size: {size}}}'


def render(entries):
    rows = "\n".join(
        f"\t{tag!r}: {{\n"
        f"\t\tTag:     {tag!r},\n"
        f"\t\tAff:     {go_file(aff)},\n"
        f"\t\tDic:     {go_file(dic)},\n"
        f"\t\tLicense: {go_file(lic)},\n"
        f"\t}},".replace("'", '"')
        for tag, aff, dic, lic in entries
    )
    return f'''// Code generated by scripts/gen-dict-manifest.py. DO NOT EDIT.

package spell

// The dictionaries kith can install, pinned to one upstream commit.
//
// A SHA-256 mismatch is a refusal (see install.go). Regenerate with `make dict-manifest`.

// dictionaryRepo and dictionaryCommit are the source and the pin.
const (
	dictionaryRepo   = "{REPO}"
	dictionaryCommit = "{COMMIT}"
	dictionaryDate   = "{COMMIT_DATE}"
	dictionaryBase   = "https://raw.githubusercontent.com/{REPO}/{COMMIT}/"
)

// dictionarySources is every installable dictionary, by the tag users type.
var dictionarySources = map[string]Source{{
{rows}
}}
'''


if __name__ == "__main__":
    main()
