// Code generated by scripts/gen-model-manifest.py. DO NOT EDIT.

package models

// The models kith can install, pinned to one upstream revision.
//
// A SHA-256 mismatch is a refusal (see install.go). Regenerate with `make model-manifest`.

// The source and the pin.
const (
	modelRepo   = "HuggingFaceTB/SmolLM2-360M-Instruct-GGUF"
	modelCommit = "593b5a2e04c8f3e4ee880263f93e0bd2901ad47f"
	modelDate   = "2024-10-31"
	modelBase   = "https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF/resolve/593b5a2e04c8f3e4ee880263f93e0bd2901ad47f/"
)

// modelSources is every model that can be installed, by the tag it installs as.
var modelSources = map[string]Source{
	"smollm2-360m": {
		Tag:     "smollm2-360m",
		Name:    "SmolLM2 360M Instruct (Q8_0)",
		File:    File{Path: "smollm2-360m-instruct-q8_0.gguf", SHA256: "48ab3034d0dd401fbc721eb1df3217902fee7dab9078992d66431f09b7750201", Size: 386404992},
		Recall:  0.339,
		License: "Apache-2.0",
	},
}
