// Code generated by scripts/gen-dict-manifest.py. DO NOT EDIT.

package spell

// The dictionaries kith can install, pinned to one upstream commit.
//
// A SHA-256 mismatch is a refusal (see install.go). Regenerate with `make dict-manifest`.

// dictionaryRepo and dictionaryCommit are the source and the pin.
const (
	dictionaryRepo   = "LibreOffice/dictionaries"
	dictionaryCommit = "32b006a2c22a4ac7e8ed3f03346f7b3d85a970a4"
	dictionaryDate   = "2026-08-22"
	dictionaryBase   = "https://raw.githubusercontent.com/LibreOffice/dictionaries/32b006a2c22a4ac7e8ed3f03346f7b3d85a970a4/"
)

// dictionarySources is every installable dictionary, by the tag users type.
var dictionarySources = map[string]Source{
	"de_DE": {
		Tag:     "de_DE",
		Aff:     File{Path: "de/de_DE_frami.aff", SHA256: "646bf3333ac69c23e9d794533ee5241d6f755c359e8fe10a648f87613743d594", Size: 19067},
		Dic:     File{Path: "de/de_DE_frami.dic", SHA256: "4ca3c958b0e5545910999bc246f668840bf8ede3df8e5e6790d05edd5a586c38", Size: 4356903},
		License: File{Path: "de/README_de_DE_frami.txt", SHA256: "c141f4f79c428b7348b5012836f4ad3db4d124f288f15effc22696dc876512ae", Size: 752},
	},
	"en_GB": {
		Tag:     "en_GB",
		Aff:     File{Path: "en/en_GB.aff", SHA256: "0fd6ed120ef28957847d98ba5149b117e27116cf81b5aa36208453f6755a36fd", Size: 44158},
		Dic:     File{Path: "en/en_GB.dic", SHA256: "04e90f34f5263bf26780e9c4a442e9ad16584e227af49ddd1b3b21b01df5b29c", Size: 1230571},
		License: File{Path: "en/README_en_GB.txt", SHA256: "18b5833de60a52ffcb6e5b6b5048bb5a5d910acfecd5b096985b77058223880c", Size: 10644},
	},
	"en_US": {
		Tag:     "en_US",
		Aff:     File{Path: "en/en_US.aff", SHA256: "e746c882dd6f303c2c46e7452804b9201115a6942cfeb15f18f8edf774d2e24e", Size: 3205},
		Dic:     File{Path: "en/en_US.dic", SHA256: "f0b1a234bd178bdd01875b2a392a9647f888b8fe879f79c52aae62c2759b3647", Size: 551762},
		License: File{Path: "en/README_en_US.txt", SHA256: "168b4c01cb841f766a72f310b065c04d09cff46376c37a81d799593ce751c371", Size: 15732},
	},
	"es_ES": {
		Tag:     "es_ES",
		Aff:     File{Path: "es/es_ES.aff", SHA256: "e73a9bf8e1383f4986a5dc9e2fbed49371c0c61f511c626d15586bd433c1cad9", Size: 169202},
		Dic:     File{Path: "es/es_ES.dic", SHA256: "6975dddec3d5d2c676069537bc67b4b5f786c65c5d4cf6703a82acf779ac9ec1", Size: 715989},
		License: File{Path: "es/LICENSE.md", SHA256: "2b70fd5cb8d3b34cc6ae322c969557a2270b99017594addb2531ef5ffd9e1b17", Size: 991},
	},
	"fr_FR": {
		Tag:     "fr_FR",
		Aff:     File{Path: "fr_FR/dictionaries/fr.aff", SHA256: "c176610cd5dc4846806a65ddd029f422d87978bf58f224aa44222662a16a2de5", Size: 199870},
		Dic:     File{Path: "fr_FR/dictionaries/fr.dic", SHA256: "b78a868e31dd6e373b6c3217969afb898a9acde828a5e7ef97308da42218c88c", Size: 1236490},
		License: File{Path: "fr_FR/dictionaries/README_dict_fr.txt", SHA256: "4a25abf740ad6ba5e8d0cfc0d2ffadc3c13c303f8fe389f323b061a389350f83", Size: 2758},
	},
	"he_IL": {
		Tag:     "he_IL",
		Aff:     File{Path: "he_IL/he_IL.aff", SHA256: "6caf86b3a545be5614f135d33a48baa244a59aca43f051dda6173d5d9cbc7700", Size: 78883},
		Dic:     File{Path: "he_IL/he_IL.dic", SHA256: "5f5331f90ed775bd527f6fb7ad1ead9a1b7d8ce46ad640c2387d9d1dc91d3058", Size: 7796259},
		License: File{Path: "he_IL/README_he_IL.txt", SHA256: "3212469adc6113e77939c20de2c29b9cec6c917d0cae80f2554cac092198e682", Size: 937},
	},
	"it_IT": {
		Tag:     "it_IT",
		Aff:     File{Path: "it_IT/it_IT.aff", SHA256: "951afaa19272f13555b8823e8bcf9ccf78f8fe1a07835bdfb912ab3e4d537c2b", Size: 70054},
		Dic:     File{Path: "it_IT/it_IT.dic", SHA256: "bae1e3501dcd2a923669592493b3fde6c02aae7c7aab83bf5e5b49077e73dd64", Size: 1295083},
		License: File{Path: "it_IT/README_it_IT.txt", SHA256: "34c3e93595cf3cf5f3afc9bc0d98eea12593750383f1e82ed1d3ca29f9681283", Size: 38902},
	},
	"nl_NL": {
		Tag:     "nl_NL",
		Aff:     File{Path: "nl_NL/nl_NL.aff", SHA256: "f0233d4f721f4661cf5f4d05ed2739549322bf3b6b66764b55a38257e1e16e6f", Size: 46557},
		Dic:     File{Path: "nl_NL/nl_NL.dic", SHA256: "bc28af45307700a9927ad5719184da44dfd7eed4f707b8c1477f6d8a21b586a6", Size: 2488246},
		License: File{Path: "nl_NL/LICENSE.txt", SHA256: "2189c248cbc054445aeac6cd65b87eebd0a115efeb55ed498b0f2a73441805dd", Size: 25820},
	},
	"pl_PL": {
		Tag:     "pl_PL",
		Aff:     File{Path: "pl_PL/pl_PL.aff", SHA256: "82973651651aa930335c865b339b98db376ca3dbf3a661b70b9eeb71fdf41dca", Size: 257542},
		Dic:     File{Path: "pl_PL/pl_PL.dic", SHA256: "c0848440599eb88e5aca500418d5f389e562ec2c157b63dbe39d354658ffba49", Size: 5252096},
		License: File{Path: "pl_PL/README_pl_PL.txt", SHA256: "e691ed1e79934293b0cd6996a14af1520ff893c02f920c09ed0c90aa5f0a8abc", Size: 593},
	},
	"pt_BR": {
		Tag:     "pt_BR",
		Aff:     File{Path: "pt_BR/pt_BR.aff", SHA256: "21d8ad2a769a60e17e2b5ea4ef11d4d593a58b9e2a82d642ef82d6a4c5523865", Size: 979792},
		Dic:     File{Path: "pt_BR/pt_BR.dic", SHA256: "a38bfb26b68ece2834e79fe83e48d5792652970ace12db89d1b9674bf9933183", Size: 4477695},
		License: File{Path: "pt_BR/README_pt_BR.txt", SHA256: "9974ce691fdc1fe731717d7a2dc668244405fdc2bf9bf3367eb9b29e85177c88", Size: 16348},
	},
	"ru_RU": {
		Tag:     "ru_RU",
		Aff:     File{Path: "ru_RU/ru_RU.aff", SHA256: "38ce7d4af78e211e9bafe4bf7e3d6a2c420591136cb738ec6648f8fdf6524cd7", Size: 71236},
		Dic:     File{Path: "ru_RU/ru_RU.dic", SHA256: "f6047416a0204adbecf3a451b874ec8a97ee37e2cbc714466ef04d8dbcc0d6fc", Size: 3473191},
		License: File{Path: "ru_RU/README_ru_RU.txt", SHA256: "262af2f6ad70a61e5ee1332ff44fa8ee50edca819cf33207d8ad6ba6a0c9be52", Size: 1886},
	},
	"uk_UA": {
		Tag:     "uk_UA",
		Aff:     File{Path: "uk_UA/uk_UA.aff", SHA256: "2219dd15e9802adebc45722c60943b1472640260491af38dd3e43b07e75585e6", Size: 211759},
		Dic:     File{Path: "uk_UA/uk_UA.dic", SHA256: "2e5a9e67be63bdb089b3459addb5d71113319d13768e277bcae20f3cc1ad5a93", Size: 8919324},
		License: File{Path: "uk_UA/README_uk_UA.txt", SHA256: "664436fee625b4a3e712483947d1711a2f467670f4c389bcf10abca2a564e1dc", Size: 362},
	},
}
