// Code generated by scripts/gen-freq-manifest.py. DO NOT EDIT.

package spell

// The frequency lists kith can install, pinned to one upstream commit.
//
// A SHA-256 mismatch is a refusal (see frequency.go). Regenerate with `make freq-manifest`.

// frequencyRepo and frequencyCommit are the source and the pin.
const (
	frequencyRepo   = "hermitdave/FrequencyWords"
	frequencyCommit = "525f9b560de45753a5ea01069454e72e9aa541c6"
	frequencyDate   = "2022-02-07"
	frequencyBase   = "https://raw.githubusercontent.com/hermitdave/FrequencyWords/525f9b560de45753a5ea01069454e72e9aa541c6/"
)

// frequencyMinCount is how often a word must appear upstream to be kept on install.
// It lives here because the recorded Words/Kept figures are measured with it.
const frequencyMinCount = 3

// frequencyLicense is upstream's license file, installed beside every list.
var frequencyLicense = File{Path: "LICENSE", SHA256: "e08d916cc953f85f7dfa0df530f6d7931f14ce804d053602662d8649b5fac829", Size: 1068}

// frequencySources is every installable frequency list, by dictionary tag (e.g. he_IL).
var frequencySources = map[string]FreqSource{
	"de_DE": {
		Tag:   "de_DE",
		Lang:  "de",
		List:  File{Path: "content/2018/de/de_full.txt", SHA256: "a5fc13f4efaaf70fd9226d11295fd3cd4c2264852ee1fad22c0abaf64acec8dc", Size: 17479451},
		Words: 355551,
		Kept:  4806940,
	},
	"en_GB": {
		Tag:   "en_GB",
		Lang:  "en",
		List:  File{Path: "content/2018/en/en_full.txt", SHA256: "7fea67ab954e2c01df6c608c9826e594cf36f8823b3243554f88245fb75dc506", Size: 19977552},
		Words: 538513,
		Kept:  6142689,
	},
	"en_US": {
		Tag:   "en_US",
		Lang:  "en",
		List:  File{Path: "content/2018/en/en_full.txt", SHA256: "7fea67ab954e2c01df6c608c9826e594cf36f8823b3243554f88245fb75dc506", Size: 19977552},
		Words: 538513,
		Kept:  6142689,
	},
	"es_ES": {
		Tag:   "es_ES",
		Lang:  "es",
		List:  File{Path: "content/2018/es/es_full.txt", SHA256: "b4794c425f3500c21a0ff9367175e36795a978c928a36670e9ad6ae206fb7728", Size: 14547688},
		Words: 475596,
		Kept:  5683942,
	},
	"fr_FR": {
		Tag:   "fr_FR",
		Lang:  "fr",
		List:  File{Path: "content/2018/fr/fr_full.txt", SHA256: "dda23c3025fc195b3a7996af26371dcf3abd1aa2cd7218dbbb7c92a49780ab0c", Size: 10161151},
		Words: 338183,
		Kept:  4037021,
	},
	"he_IL": {
		Tag:   "he_IL",
		Lang:  "he",
		List:  File{Path: "content/2018/he/he_full.txt", SHA256: "a69a3f390eb53183bf191c4eac18282592992aef9ff184c5dcf8919f5ea0f773", Size: 19215890},
		Words: 455962,
		Kept:  7196479,
	},
	"it_IT": {
		Tag:   "it_IT",
		Lang:  "it",
		List:  File{Path: "content/2018/it/it_full.txt", SHA256: "b23b0c6a3f59c1da1c7caa667b9df5699e95323fee20a05f343c7d7dae73c4be", Size: 9677728},
		Words: 333371,
		Kept:  4003969,
	},
	"nl_NL": {
		Tag:   "nl_NL",
		Lang:  "nl",
		List:  File{Path: "content/2018/nl/nl_full.txt", SHA256: "50c9691c82d2eb267f6db4ab042cab8fe366f32da958ebae0a220764db1e0cf3", Size: 15457399},
		Words: 360769,
		Kept:  4639669,
	},
	"pl_PL": {
		Tag:   "pl_PL",
		Lang:  "pl",
		List:  File{Path: "content/2018/pl/pl_full.txt", SHA256: "8b69a097e502a32a42db6ca37a74781f66ddc4027fe5d66b6d98b6467abae3cf", Size: 19211289},
		Words: 628569,
		Kept:  8017029,
	},
	"pt_BR": {
		Tag:   "pt_BR",
		Lang:  "pt_br",
		List:  File{Path: "content/2018/pt_br/pt_br_full.txt", SHA256: "533b3abaab3b1ea9cec7a150fc8aaf8d428c6f241979cc2224b7ee82f8a369b2", Size: 9882799},
		Words: 370993,
		Kept:  4327249,
	},
	"ru_RU": {
		Tag:   "ru_RU",
		Lang:  "ru",
		List:  File{Path: "content/2018/ru/ru_full.txt", SHA256: "32dfd94138aea2667ec455dcc8512029e39bd4b8ea70b09410d569b69d511a30", Size: 28999417},
		Words: 543341,
		Kept:  10721209,
	},
	"uk_UA": {
		Tag:   "uk_UA",
		Lang:  "uk",
		List:  File{Path: "content/2018/uk/uk_full.txt", SHA256: "bfa15b3512a41771ac8ecf47f5ef8314badb76f867fb9a6afbb409265b41709f", Size: 5560013},
		Words: 100154,
		Kept:  1814021,
	},
}
